# Railway deployment configuration
# Environment variables to be set in Railway dashboard:
# DATABASE_URL=jdbc:mysql://[host]:[port]/[database]?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# DATABASE_USER=[username]
# DATABASE_PASSWORD=[password]
# JWT_SECRET=[your-secret-key]
# MAIL_USERNAME=[your-email]
# MAIL_PASSWORD=[your-app-password]
# MAIL_HOST=smtp.gmail.com
# MAIL_PORT=587
# PORT=8080

version: 0.1.0
services:
  backend:
    build: .
    port: 8080
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PORT=8080
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=event_management_db
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
